### ISSUE TITLE
Not Responsive 

### ISSUE THREAD

**Issue by SayedZahirAli** [mqchen/jquery.diamonds.js#15]
Hi 

It is making a distorted layout as it doesn't get sorted properly on viewport of 300px. can you please resolve it

**Comment by pk0nstantin** [comment]
Hi. 
Thank you - it's a great library, I`ve recently started to use it.
It is very important to find a solution to this issue. 
A similar situation - I can not make the resize for iphone.
I would be glad of any help from you!

###

demo URL - http://premion.com.ua/ (login:premion / password:premion)
