### ISSUE TITLE
Change images?

### ISSUE THREAD

**Issue by artdesign84** [mqchen/jquery.diamonds.js#16]
I'd like to use this gallery but I only want 4 diamonds in the arrangement shown below. Is this possible?

Also, how do I change the images so it doesn't display your flickr account? I'd prefer to have it link to images on my personal server or desktop and not on flickr. 

Thanks in advance for your guidance. 
![screen shot 2014-12-29 at 6 12 43 pm](https://cloud.githubusercontent.com/assets/10344243/5574504/56fa0396-8f86-11e4-86b2-910f085c69e7.png)

**Comment by mqchen** [comment]
Hi!
I'm sorry for the late reply, but you unfortunately can't create that layout with this plugin. If you'd give it 4 images and a max row size of 2, you would get:

![screen shot 2015-01-08 at 15 49 26](https://cloud.githubusercontent.com/assets/259729/5664106/fb117b3e-974d-11e4-8130-901c3c452558.png)

However, you could manage it if you add 2 transparent images first:

![screen shot 2015-01-08 at 15 52 53](https://cloud.githubusercontent.com/assets/259729/5664170/793f5c38-974e-11e4-9db2-15fc98649add.png)

I only used Flickr for the demo, but please refer to the Readme on instructions on how to use it on your DOM: https://github.com/mqchen/jquery.diamonds.js#usage
